'use strict';

module.exports = {
  europe: [
    'AL',
    'AD',
    'AM',
    'AT',
    'AZ',
    'BY',
    'BE',
    'BA',
    'BG',
    'CH',
    'CY',
    'CZ',
    'DE',
    'DK',
    'EE',
    'ES',
    'FI',
    'FR',
    'GE',
    'GR',
    'HR',
    'HU',
    'IE',
    'IS',
    'IT',
    'KZ',
    'XK',
    'LV',
    'LI',
    'LT',
    'LU',
    'MT',
    'MC',
    'MD',
    'ME',
    'MK',
    'NL',
    'NO',
    'PL',
    'PT',
    'RO',
    'RU',
    'SM',
    'RS',
    'SK',
    'SI',
    'SE',
    'TR',
    'GB',
    'UK',
    'VA',
  ],
  countryAliases: {
    UK: 'GB',
  },
  localizationByCountry: {
    AT: { language: 'german', currency: 'EUR' },
    ES: { language: 'spanish', currency: 'EUR' },
    FR: { language: 'french', currency: 'EUR' },
    GR: { language: 'greek', currency: 'EUR' },
    IT: { language: 'italian', currency: 'EUR' },
    RU: { language: 'russian', currency: 'EUR' },
    UA: { language: 'ukrainian', currency: 'EUR' },
  },
};
