'use strict';

module.exports = {
  europe: [
    'AL',
    'AD',
    'AM',
    'AT',
    'AZ',
    'BY',
    'BE',
    'BA',
    'BG',
    'CH',
    'CY',
    'CZ',
    'DE',
    'DK',
    'EE',
    'ES',
    'FI',
    'FR',
    'GE',
    'GR',
    'HR',
    'HU',
    'IE',
    'IS',
    'IT',
    'KZ',
    'XK',
    'LV',
    'LI',
    'LT',
    'LU',
    'MT',
    'MC',
    'MD',
    'ME',
    'MK',
    'NL',
    'NO',
    'PL',
    'PT',
    'RO',
    'RU',
    'SM',
    'RS',
    'SK',
    'SI',
    'SE',
    'TR',
    'GB',
    'UK',
    'VA',
  ],
  countryAliases: {
    UK: 'GB',
  },
  localizationByCountry: {
    AT: { language: 'german', currency: 'EUR' },
    BE: { language: 'french', currency: 'EUR' },
    CH: { language: 'german', currency: 'CHF' },
    CZ: { language: 'czech', currency: 'CZK' },
    DE: { language: 'german', currency: 'EUR' },
    DK: { language: 'danish', currency: 'DKK' },
    ES: { language: 'spanish', currency: 'EUR' },
    FI: { language: 'finnish', currency: 'EUR' },
    FR: { language: 'french', currency: 'EUR' },
    GB: { language: 'english', currency: 'GBP' },
    GR: { language: 'greek', currency: 'EUR' },
    HU: { language: 'hungarian', currency: 'HUF' },
    IE: { language: 'english', currency: 'EUR' },
    IT: { language: 'italian', currency: 'EUR' },
    NL: { language: 'dutch', currency: 'EUR' },
    NO: { language: 'norwegian', currency: 'NOK' },
    PL: { language: 'polish', currency: 'PLN' },
    PT: { language: 'portuguese', currency: 'EUR' },
    RO: { language: 'romanian', currency: 'RON' },
    RU: { language: 'russian', currency: 'EUR' },
    SE: { language: 'swedish', currency: 'SEK' },
    TR: { language: 'turkish', currency: 'TRY' },
    UA: { language: 'ukrainian', currency: 'UAH' },
  },
};
